src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceService.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/dto/response/BaseResponse.java, src/main/java/com/keepgoing/keepserver/global/exception/device/DeviceException.java
- #9 
기자재 삭제 기능 개발 하였습니다.
기기 등록 로직만 추가하면 대충 기기 관련 기능은 다 구현된 것 같습니다.
이후에 유저 브랜치로 넘어가서 권한 부분 좀 수정할 예정입니다.
=> Feat :: device deletion logic

src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
실수로 `email` 을 `encoding` 해서 `password` 를 `encoding` 하도록 수정했습니다.
빠르게 `merge` 해서 배포 하도록 하겠습니다~
=> Fix :: encoding issue resolved

src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceService.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
- #9 
1. 기자재 등록 api 구현
2. dtoToEntity 반환값 수정
=> Feat :: device create api

src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java, src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
- #29 
/userinfo 반환값에 기자재 대여 정보 로직 추가했습니다.
=> Refactor :: add rental info to /userinfo return value [1/2]

src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/repository/BookRepository.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java, src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
resolved #29 
/userinfo 반환값에 도서 대여 정보 로직 추가했습니다.
=> Refactor :: add rental info to /userinfo return value [2/2]

src/main/java/com/keepgoing/keepserver/domain/user/payload/response/JwtResponse.java, src/main/java/com/keepgoing/keepserver/domain/user/security/service/UserDetailsImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
로그인 시 반환되는 값에 password가 있어서 급하게 이름으로 수정했습니다-!
웹에서 OOO님 값 받아가실때 name 가져가시면 됩니다.
=> Fix :: fix jwt response return value

src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java, src/main/java/com/keepgoing/keepserver/domain/image/dto/ImageDTO.java, src/main/java/com/keepgoing/keepserver/domain/image/service/ImageService.java
파일 업로드 로직 수정 및 기기 등록일 추가 했습니다.
클라이언트분들은 /uplaod 에서 파일 올리고 반환된 url을 string 으로 저장해서 등록 api 에 다른 값과 함께 보내주시면 됩니다.
=> Refactor :: refactor upload logic

src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/student/consts/StudentFindType.java, src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java, src/main/java/com/keepgoing/keepserver/domain/student/entity/Student.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/StudentRepository.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentDto.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentFindDto.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentIdDto.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentRequestDto.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/dto/StudentResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/exception/book/BookError.java, src/main/java/com/keepgoing/keepserver/global/exception/book/BookException.java, src/test/java/com/keepgoing/keepserver/KeepServerApplicationTests.java
- #43 
기존 `grade`,` group`, `groupNum` 으로 나뉘어져있던 `entity`를 `studentId`로 수정했습니다.
단일책임원칙을 위반한 함수`findStudent`를 `findStudentNum`과 `findStudentName`으로 수정했습니다.
또한 `findStudent`에 예외처리 추가했습니다.
=> Fix :: find student error v2

src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookDto.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookRequestDto.java, src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/security/WebSecurityConfig.java, src/main/java/com/keepgoing/keepserver/global/util/GenerateCertCharacter.java
-  
코드 전체적인 리팩토링을 하였습니다. 
단일책임원칙이 지켜지지 않는 부분은 수정하였습니다.
또 CORS error 수정하였습니다
=> Fix :: Book service error

src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java
- #44
swagger 수정하였습니다.
GetMapping을 PostMapping으로 수정하였습니다
=> Fix :: find student error v3

src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java, src/main/java/com/keepgoing/keepserver/domain/device/enums/DeviceStatus.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/rent/service/RentServiceImpl.java
1. 대여 성공 시 반환 값에 대여 시작일 추가
2. device & book mapper 수정
=> Refactor :: refactor rental return value

src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookDto.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/dto/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
=> Fix :: fix book register return value

src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
=> Fix :: fix findAll() return value

src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceEditRequest.java, src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceService.java, src/main/java/com/keepgoing/keepserver/domain/device/service/DeviceServiceImpl.java
누락되었던 기자재 수정 api 개발했습니다.
swagger 문서 참고 하시면 됩니다.
=> Feat :: create device edit api

src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java, src/main/java/com/keepgoing/keepserver/domain/student/repository/StudentRepository.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
`studentService` `edit` 에서 입력값이 `id`가 아닌 `studentId`로 되어있어 수정했습니다.
=> Fix :: edit student service

src/main/java/com/keepgoing/keepserver/domain/device/presentation/DeviceController.java, src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java
userinfo 반환값 오타 수정 및 스웨거 desc 추가 했습니다.
=> Fix :: fix typo + swagger desc

src/main/java/com/keepgoing/keepserver/domain/Return/presentation/ReturnController.java, src/main/java/com/keepgoing/keepserver/domain/Return/service/ReturnService.java, src/main/java/com/keepgoing/keepserver/domain/Return/service/ReturnServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/book/repository/BookRepository.java, src/main/java/com/keepgoing/keepserver/domain/rent/presentation/RentController.java, src/main/java/com/keepgoing/keepserver/domain/rent/service/RentService.java, src/main/java/com/keepgoing/keepserver/domain/rent/service/RentServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/exception/book/BookError.java, src/main/java/com/keepgoing/keepserver/global/exception/book/BookException.java, src/main/java/com/keepgoing/keepserver/global/exception/device/DeviceError.java, src/main/java/com/keepgoing/keepserver/global/exception/device/DeviceException.java
#58 기자재/반납 로직 구현 했습니다.
또한 현재 도서 대여가 `deviceName` 으로 이루어 지고 있어서 `nfcCode` 로 대출 및 반납 되도록 수정 했습니다.
=> Feat :: device and book return logic & fix book request value

src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java
mapper에 static은 적절하지 않은거 같아서 제거 했습니다.
=> Refactor :: remove static

src/main/java/com/keepgoing/keepserver/domain/Return/service/ReturnServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/book/entity/enums/BookState.java, src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookDto.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookRequestDto.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/response/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/device/entity/Device.java, src/main/java/com/keepgoing/keepserver/domain/device/entity/enums/DeviceStatus.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceEditRequest.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/rent/service/RentServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/returns/presentation/ReturnController.java, src/main/java/com/keepgoing/keepserver/domain/returns/service/ReturnService.java, src/main/java/com/keepgoing/keepserver/domain/returns/service/ReturnServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/payload/request/UserProfileDto.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/response/CustomResponseEntity.java, src/main/java/com/keepgoing/keepserver/global/response/ExceptionResponseEntity.java, src/main/java/com/keepgoing/keepserver/global/response/ResponseEntity.java
전체적으로 package style 통합하고,
return은 패키지명이 불가능 하나 대문자는 혼란을 줄 거 같아 returns로 수정했습니다.
=> Style :: overall package style change

src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
미루고 미루던 유저 도메인 서비스 로직 부터 전체적으로 리팩토링 했습니다.
1. `controller` 에서 수행되던 `service layer` 작업 이관
2. `user-service-iml` 단일 책임 원칙 적용
=> Refactor :: refactor user domain related service logics

src/main/java/com/keepgoing/keepserver/domain/student/controller/StudentController.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentService.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java
`imgUrl` 업로드시 `학반번호` 로 매핑해서 `DB` 에 저장되게 구현했습니다.
=> Feat :: Mapping Image By StudentId

src/main/java/com/keepgoing/keepserver/domain/book/domain/repository/BookRepository.java, src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/util/DateRange.java
=> Add: Book date-specific alarm feature

src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
mapper에서 writer, registrationDate 반환되게 수정했습니다.
=> Edit :: BookMapper

build.gradle, src/main/java/com/keepgoing/keepserver/domain/book/domain/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/book/domain/enums/BookState.java, src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookDto.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/request/BookRequestDto.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/response/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/device/domain/entity/Device.java, src/main/java/com/keepgoing/keepserver/domain/device/domain/enums/DeviceStatus.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceDto.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/request/DeviceEditRequest.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/notice/domain/mapper/NoticeMapper.java, src/main/java/com/keepgoing/keepserver/domain/notice/mapper/NoticeMapper.java, src/main/java/com/keepgoing/keepserver/domain/notice/payload/req/NoticeRequestDto.java, src/main/java/com/keepgoing/keepserver/domain/notice/service/NoticeServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/rent/service/RentServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/returns/service/ReturnServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/student/domain/repository/dto/StudentResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/student/service/StudentServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java, src/main/java/com/keepgoing/keepserver/domain/user/domain/entity/user/User.java, src/main/java/com/keepgoing/keepserver/domain/user/domain/enums/Status.java, src/main/java/com/keepgoing/keepserver/domain/user/domain/repository/user/UserQueryRepositoryImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/dto/request/StatusRequest.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
- #83 
학생 상태 보고 기능 구현하였습니다.
user 에서 로그인 한 학생이 상태를 보냈을 때,
선생님이 조회하는 student에서도 상태를 불러와야하므로 
user 회원가입시 메일은 @dgsw.hs.kr 메일로 해야합니다.
=> Feat :: 상황 보고 기능 구현

src/main/java/com/keepgoing/keepserver/domain/book/domain/entity/Book.java, src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/response/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/device/domain/entity/Device.java, src/main/java/com/keepgoing/keepserver/domain/device/mapper/DeviceMapper.java, src/main/java/com/keepgoing/keepserver/domain/device/payload/response/DeviceResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/returns/service/ReturnServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/user/domain/repository/user/UserQueryRepositoryImpl.java
전체 책과 기기 조회시에 마지막 대여자의 메일을 반환합니다
=> Add :: 마지막 대여자 return 

src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/damage/entity/Damage.java, src/main/java/com/keepgoing/keepserver/domain/damage/mapper/DamageMapper.java, src/main/java/com/keepgoing/keepserver/domain/damage/payload/request/DamageCreateRequest.java, src/main/java/com/keepgoing/keepserver/domain/damage/payload/response/DamageResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/damage/presentation/DamageController.java, src/main/java/com/keepgoing/keepserver/domain/damage/repository/DamageRepository.java, src/main/java/com/keepgoing/keepserver/domain/damage/service/DamageService.java, src/main/java/com/keepgoing/keepserver/domain/damage/service/DamageServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/exception/damage/DamageError.java, src/main/java/com/keepgoing/keepserver/global/exception/damage/DamageException.java
- #86
Create Damage, Read Damage, Delete Damage 구현하였습니다.
=> Feat :: Damage Create, Read, Delete

src/main/java/com/keepgoing/keepserver/domain/book/domain/repository/BookRepository.java, src/main/java/com/keepgoing/keepserver/domain/book/presentation/BookController.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookService.java, src/main/java/com/keepgoing/keepserver/domain/book/service/BookServiceImpl.java
=> Feat :: select recommend book

src/main/java/com/keepgoing/keepserver/domain/damage/entity/Damage.java, src/main/java/com/keepgoing/keepserver/domain/damage/enums/IssueType.java, src/main/java/com/keepgoing/keepserver/domain/damage/payload/request/DamageCreateRequest.java, src/main/java/com/keepgoing/keepserver/domain/damage/repository/DamageRepository.java, src/main/java/com/keepgoing/keepserver/domain/damage/service/DamageServiceImpl.java, src/main/java/com/keepgoing/keepserver/global/exception/damage/DamageError.java, src/main/java/com/keepgoing/keepserver/global/exception/damage/DamageException.java
closes #92 
신고 유형 String → Enum 으로 변경하였고, 
도서/기자재 신고 유형 IssueType 에서 함께 관리합니다.
=> Refactor :: change issue type to enum

src/main/java/com/keepgoing/keepserver/domain/damage/presentation/DamageController.java, src/main/java/com/keepgoing/keepserver/domain/damage/service/DamageService.java, src/main/java/com/keepgoing/keepserver/domain/damage/service/DamageServiceImpl.java
closes #94 
누락된 신고 내역 단일 조회 API를 개발 했습니다.
=> add report single view api

build.gradle, src/main/java/com/keepgoing/keepserver/domain/face/controller/FaceRecognitionController.java, src/main/java/com/keepgoing/keepserver/domain/face/entity/Face.java, src/main/java/com/keepgoing/keepserver/domain/face/repository/FaceRepository.java, src/main/java/com/keepgoing/keepserver/domain/face/service/FaceRecognitionService.java, src/main/java/com/keepgoing/keepserver/domain/face/service/FaceRecognitionServiceImpl.java, src/main/java/com/keepgoing/keepserver/domain/image/service/ImageService.java, src/main/java/com/keepgoing/keepserver/global/common/S3/S3Uploader.java, src/main/java/com/keepgoing/keepserver/global/util/AwsRekognitionClient.java
=> Feat :: 얼굴 인식 기능 개발

src/main/java/com/keepgoing/keepserver/domain/user/controller/UserController.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserService.java, src/main/java/com/keepgoing/keepserver/domain/user/service/user/UserServiceImpl.java
=> add delete user api

src/main/java/com/keepgoing/keepserver/domain/book/mapper/BookMapper.java, src/main/java/com/keepgoing/keepserver/domain/book/payload/response/BookResponseDto.java, src/main/java/com/keepgoing/keepserver/domain/user/domain/repository/user/UserQueryRepositoryImpl.java
=> Feat :: book 대여자 반환값 추가
